
:schedule: link:./SCHEDULE.adoc

= Boeing DevOps Workshop


== Overview

Welcome to the workshop! This is a collection of exercises and accompanying source code. Emphasis is on Pivotal Cloud Foundry; cloud native concepts; microservice design; Spring Boot; Spring Cloud Services, and accelerating software delivery with Concourse CI/CD pipelines. It is typically conducted over a 2-3 day period. The {schedule}[Workshop Schedule] contains the timeline for the workshop and links to all presentations and labs.


== Prerequisities

=== Software

* Git
* Java JDK 1.8u*
* CF CLI
* STS (Spring Source Tool Suite an Eclipse IDE variant)
* Postman (a REST client)

To install prerequisite software, run the _DevOpsInstall.ps1_ script from https://git.web.boeing.com/fork-me/devops-setup[here].

== Workshop Repository

> Note: https://dev-docs.web.boeing.com/recipe/dev-setup-open-ssh[Ensure your SSH keys are setup for used with GitLab].

Fork then Clone the following repositories for use in the workshop:

[source,bash]
----
git clone https://github.com/Pivotal-Field-Engineering/devops-workshop
----

=== Environment Setup

Ensure that you have your environment configured correctly and can successfully build the projects. 

This workshop contains a number of labs meant to be worked through in numerical order - as each exercise builds upon the last. The only exception to this sequence is _lesson-00_. _lesson-00_ references sample applications in the _samples_ directory.  These applications can be pushed to Cloud Foundry at any time.

Your workspace is the _labs/workspace_ directory. If you get stuck implementing any of the labs, _solutions_ are available for your perusal.

Projects in this repository expect the following environment configuration

Set Envronment Variables:

* REPO_MAVEN_RELEASE=https://sres.web.boeing.com/artifactory/Maven-Releases
* REPO_GRADLE_PLUGINS=https://sres.web.boeing.com/artifactory/list/gradle-plugins-remot
* ArtifactoryUser={ YOUR_BEMSID }
* ArtifactoryKey={ YOUR_SRES_ARTIFACTORY_KEY }

=== PCF Environment Access

Instructors should have added all atendees to a workshop-specific org so all attendees have quick access to an environment. If you do not have an account yet, please see the instructor.

Verify that you can access the https://login.system.pcfpre-phx.cloud.boeing.com/login[PHX PreProd PCF Apps Manager].

