= Boeing DevOps Workshop


A collection of workshop presentations and labs exercises for use at Boeing. Focus on Pivotal Cloud Foundry, Cloud Native concepts, Microservices design, Spring Boot and Spring Cloud Services, and accelerating software delivery with Concourse CI/CD pipelines. Typically conducted over a https://github.com/Pivotal-Field-Engineering/devops-workshop/blob/master/SCHEDULE.adoc[1-1/2 day period].

== Deprecation Notice

(2017-10-25) This repository is deprecated in favor of Boeing hosted Gitlab repositories, here:

-> https://git.web.boeing.com/fork-me/workshop-presentation[Presentations]

-> https://git.web.boeing.com/fork-me/workshop-project[Workshop]

-> https://git.web.boeing.com/fork-me/dev-docs/tree/workshop/content/workshop[Labs]



== Software Prerequisities

=== Minimum requirements

-> CF-CLI

-> Java JDK

-> Git

-> Gradle

=== Recommended

-> STS (Spring Source Tool Suite an Eclipse IDE variant)

-> Postman (a REST client)


== Clone this repository

You will need to set a couple of environment variables `HTTP_PROXY` and `HTTPS_PROXY` first!

[source,bash]
---------------------------------------------------------------------
set HTTP_PROXY=http://www-proxy.web.boeing.com:31060
set HTTPS_PROXY=http://www-proxy.web.boeing.com:31060
---------------------------------------------------------------------

then

[source,bash]
---------------------------------------------------------------------
git clone https://github.com/Pivotal-Field-Engineering/devops-workshop
---------------------------------------------------------------------


== Helpful links

-> https://pcf-start.web.pcfpre-phx.apps.boeing.com/workshop.html[PCF Workshops at Boeing]

-> https://pcf-start.web.pcfpre-phx.apps.boeing.com/secured[Cloud Foundry Account Request]

-> https://pcf-start.wpi.pcfpre-phx.apps.boeing.com/faq.html[Software installation and usage FAQ]
