:compat-mode:
= Adding Persistence to Boot Application

In this lab we'll utilize Spring Boot, Spring Data, and Spring Data REST to create a fully-functional hypermedia-driven RESTful web service. We'll then deploy it to Pivotal Cloud Foundry.

== Create a Hypermedia-Driven RESTful Web Service with Spring Data REST (using JPA)

This application will allow us to create, read update and delete records in an http://www.h2database.com/html/quickstart.html[in-memory] relational repository. We'll continue building upon the Spring Boot application we built out in Lab 1.  The first stereotype we will need is the domain model itself, which is `City`.

== Add the domain object - City

. Create the package `io.pivotal.domain` and in that package create the class `City`. Into that file you can paste the following source code, which represents cities based on postal codes, global coordinates, etc:
+
[source, java, numbered]
---------------------------------------------------------------------
package io.pivotal.domain;

@Data
@Entity
@Table(name="city")
public class City implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue
    private long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String county;

    @Column(nullable = false)
    private String stateCode;

    @Column(nullable = false)
    private String postalCode;

    @Column
    private String latitude;

    @Column
    private String longitude;

}

---------------------------------------------------------------------
+
Notice that we're using http://docs.oracle.com/javaee/6/tutorial/doc/bnbpz.html[JPA] annotations on the class and its fields. We're also employing https://projectlombok.org/features/all[Lombok], so we don't have to write a bunch of boilerplate code (e.g., getter and setter methods).  You'll need to use your IDE's features to add the appropriate import statements.
+
-> Hint: imports should start with `javax.persistence` and `lombok`

. Create the package +io.pivotal.repositories+ and in that package create the interface +CityRepository+. Paste the following code and add appropriate imports:
+
[source,java]
---------------------------------------------------------------------
package io.pivotal.repositories;

@RepositoryRestResource(collectionResourceRel = "cities", path = "cities")
public interface CityRepository extends PagingAndSortingRepository<City, Long> {
}
---------------------------------------------------------------------
+
You’ll need to use your IDE’s features to add the appropriate import statements.
+
-> Hint: imports should start with `org.springframework.data.rest.core.annotation` and `org.springframework.data.repository`

== Run the _cloud-native-spring_ Application

. Return to the Terminal session you opened previously

. Run the application
+
[source,bash]
---------------------------------------------------------------------
gradle clean bootRun
---------------------------------------------------------------------

. Access the application using +curl+ or your web browser using the newly added REST repository endpoint at http://localhost:8080/cities. You'll see that the primary endpoint automatically exposes the ability to page, size, and sort the response JSON.
+
[source,bash]
---------------------------------------------------------------------
curl -i http://localhost:8080/cities

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: application/hal+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 28 Apr 2016 14:44:06 GMT

{
  "_embedded" : {
    "cities" : [ ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/cities"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile/cities"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}
---------------------------------------------------------------------

. To exit the application, type *Ctrl-C*.

So what have you done? Created four small classes and one build file, resulting in a fully-functional REST microservice. The application's +DataSource+ is created automatically by Spring Boot using the in-memory database because no other +DataSource+ was detected in the project. 

Next we'll import some data.

== Importing Data

. Add this https://raw.githubusercontent.com/Pivotal-Field-Engineering/devops-workshop-boeing/master/labs/02/import.sql[import.sql] file found in *devops-workshop-boeing/labs/02* to +src/main/resources+. This is a rather large dataset containing all of the postal codes in the United States and its territories. This file will automatically be picked up by http://hibernate.org/orm/what-is-an-orm/[Hibernate] and imported into the in-memory database.

. Restart the application.
+
[source,bash]
---------------------------------------------------------------------
gradle clean bootRun
---------------------------------------------------------------------

. Access the application again. Notice the appropriate hypermedia is included for +next+, +previous+, and +self+. You can also select pages and page size by utilizing +?size=n&page=n+ on the URL string. Finally, you can sort the data utilizing +?sort=fieldName+ (replace fieldName with a cities attribute).
+
[source,bash]
---------------------------------------------------------------------
curl -i localhost:8080/cities

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application
Content-Type: application/hal+json
Transfer-Encoding: chunked
Date: Tue, 27 May 2014 19:59:58 GMT

{
  "_links" : {
    "next" : {
      "href" : "http://localhost:8080/cities?page=1&size=20"
    },
    "self" : {
      "href" : "http://localhost:8080/cities{?page,size,sort}",
      "templated" : true
    }
  },
  "_embedded" : {
    "cities" : [ {
      "name" : "HOLTSVILLE",
      "county" : "SUFFOLK",
      "stateCode" : "NY",
      "postalCode" : "00501",
      "latitude" : "+40.922326",
      "longitude" : "-072.637078",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/1"
        }
      }
    },

    // ...

    {
      "name" : "CASTANER",
      "county" : "LARES",
      "stateCode" : "PR",
      "postalCode" : "00631",
      "latitude" : "+18.269187",
      "longitude" : "-066.864993",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/20"
        }
      }
    } ]
  },
  "page" : {
    "size" : 20,
    "totalElements" : 42741,
    "totalPages" : 2138,
    "number" : 0
  }
}
---------------------------------------------------------------------

. Try the following URL Paths with +curl+ to see how the application behaves:
+
http://localhost:8080/cities?size=5
+
http://localhost:8080/cities?size=5&page=3
+
http://localhost:8080/cities?sort=postalCode,desc

Next we'll add searching capabilities.

== Adding Search

. Let's add some additional finder methods to +CityRepository+:
+
[source,java]
---------------------------------------------------------------------
@RestResource(path = "name", rel = "name")
Page<City> findByNameIgnoreCase(@Param("q") String name, Pageable pageable);

@RestResource(path = "nameContains", rel = "nameContains")
Page<City> findByNameContainsIgnoreCase(@Param("q") String name, Pageable pageable);

@RestResource(path = "state", rel = "state")
Page<City> findByStateCodeIgnoreCase(@Param("q") String stateCode, Pageable pageable);

@RestResource(path = "postalCode", rel = "postalCode")
Page<City> findByPostalCode(@Param("q") String postalCode, Pageable pageable);

@Query(value ="select c from City c where c.stateCode = :stateCode")
Page<City> findByStateCode(@Param("stateCode") String stateCode, Pageable pageable);
---------------------------------------------------------------------
+
-> Hint: imports should start with `org.springframework.data.domain`, `org.springframework.data.rest.core.annotation`, `org.springframework.data.repository.query`, and `org.springframework.data.jpa.repository`

. Run the application
+
[source,bash]
---------------------------------------------------------------------
gradle clean bootRun
---------------------------------------------------------------------

. Access the application again. Notice that hypermedia for a new +search+ endpoint has appeared.
+
[source,bash]
---------------------------------------------------------------------
curl -i "localhost:8080/cities"

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application
Content-Type: application/hal+json
Transfer-Encoding: chunked
Date: Tue, 27 May 2014 20:33:52 GMT

// prior omitted
    },
    "_links": {
        "first": {
            "href": "http://localhost:8080/cities?page=0&size=20"
        },
        "self": {
            "href": "http://localhost:8080/cities{?page,size,sort}",
            "templated": true
        },
        "next": {
            "href": "http://localhost:8080/cities?page=1&size=20"
        },
        "last": {
            "href": "http://localhost:8080/cities?page=2137&size=20"
        },
        "profile": {
            "href": "http://localhost:8080/profile/cities"
        },
        "search": {
            "href": "http://localhost:8080/cities/search"
        }
    },
    "page": {
        "size": 20,
        "totalElements": 42741,
        "totalPages": 2138,
        "number": 0
    }
}
---------------------------------------------------------------------

. Access the new +search+ endpoint:
+
http://localhost:8080/cities/search
+
[source,bash]
---------------------------------------------------------------------
curl -i "localhost:8080/cities/search"

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application
Content-Type: application/hal+json
Transfer-Encoding: chunked
Date: Tue, 27 May 2014 20:38:32 GMT

{
    "_links": {
        "postalCode": {
            "href": "http://localhost:8080/cities/search/postalCode{?q,page,size,sort}",
            "templated": true
        },
        "state": {
            "href": "http://localhost:8080/cities/search/state{?q,page,size,sort}",
            "templated": true
        },
        "nameContains": {
            "href": "http://localhost:8080/cities/search/nameContains{?q,page,size,sort}",
            "templated": true
        },
        "name": {
            "href": "http://localhost:8080/cities/search/name{?q,page,size,sort}",
            "templated": true
        },
        "findByStateCode": {
            "href": "http://localhost:8080/cities/search/findByStateCode{?stateCode,page,size,sort}",
            "templated": true
        },
        "self": {
            "href": "http://localhost:8080/cities/search"
        }
    }
}
---------------------------------------------------------------------
+
Note that we now have new search endpoints for each of the finders that we added.

. Try a few of these endpoints in https://www.getpostman.com[Postman]. Feel free to substitute your own values for the parameters.
+
http://localhost:8080/cities/search/postalCode?q=75202
+
http://localhost:8080/cities/search/name?q=Boston
+
http://localhost:8080/cities/search/nameContains?q=Fort&size=1
+ 
-> For further details on what's possible with Spring Data JPA, consult the https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#dependencies.spring-boot[reference documentation]


== Pushing to Cloud Foundry

. Build the application
+
[source,bash]
---------------------------------------------------------------------
gradle bootRepackage
---------------------------------------------------------------------

. You should already have an application manifest, +manifest.yml+, created in Lab 1; this can be reused.  You'll want to add a timeout param so that our service has enough time to initialize with its data loading:
+
[source,yml]
---------------------------------------------------------------------
---
applications:
- name: cloud-native-spring
  random-route: true
  memory: 1024M
  instances: 1
  path: ./build/libs/cloud-native-spring-1.0-SNAPSHOT-exec.jar
  buildpack: java_buildpack
  timeout: 180 # to give time for the data to import
  env:
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
---------------------------------------------------------------------

. Push to Cloud Foundry:
+
[source,bash]
---------------------------------------------------------------------
cf push

...

Showing health and status for app cloud-native-spring in org zoo-labs / space development as cphillipson@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: cloud-native-spring-apodemal-hyperboloid.cfapps.io
last uploaded: Thu Sep 28 23:29:21 UTC 2017
stack: cflinuxfs2
buildpack: java_buildpack

     state     since                    cpu      memory         disk         details
#0   running   2017-09-28 04:30:22 PM   163.7%   395.7M of 1G   159M of 1G
---------------------------------------------------------------------

. Access the application at the random route provided by CF:
+
[source,bash]
---------------------------------------------------------------------
curl -k https://cloud-native-spring-{random-word}.{domain}.com/cities
---------------------------------------------------------------------
