= Building a Spring Boot Application

In this lab we'll build and deploy a simple https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/[Spring Boot] application to Cloud Foundry whose sole purpose is to reply with a standard greeting.

== Getting started

While we could visit https://start.spring.io to create a new Spring Boot project, we will start with a skeleton

. Open a Terminal (e.g., _cmd_ or _bash_ shell)

. Change the working directory to be _devops-workshop-boeing/labs/my_work/cloud-native-spring_
+
  cd /devops-workshop-boeing/labs/my_work/cloud-native-spring

. Open this project in your editor/IDE of choice.
+
*_STS Import Help_*
+
Select _File > Import…_. In the susequent dialog choose _Gradle > Existing Gradle Project_ then click the _Next_ button. In the _Import Gradle Project_ dialog browse to the _cloud-native-spring_ directory (e.g. _devops-workshop-boeing/labs/my_work/cloud-native-spring_) then click the _Open_ button, then click the _Finish_ button.

== Add an Endpoint

Within your editor/IDE complete the following steps:

. Create a new package _io.pivotal.controller_ underneath _src/main/java_.

. Create a new class named _GreetingController_ in the aforementioned package.

. Add an _@RestController_ annotation to the class _io.pivotal.controller.GreetingController_ (i.e., _/cloud-native-spring/src/main/java/io/pivotal/controller/GreetingController.java_).
+
[source, java]
---------------------------------------------------------------------
package io.pivotal.controller;

import org.springframework.web.bind.annotation.RestController;

@RestController
public class GreetingController {

}
---------------------------------------------------------------------

. Add the following request handler to the class _io.pivotal.controller.GreetingController_ (i.e., _/cloud-native-spring/src/main/java/io/pivotal/controller/GreetingController.java_).
+
[source,java]
---------------------------------------------------------------------
@RequestMapping("/")
public String hello() {
    return "Hello World!";
}
---------------------------------------------------------------------
+
Completed:
+
[source,java]
---------------------------------------------------------------------
package io.pivotal.controller;

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;

@RestController
public class GreetingController {

    @RequestMapping("/hello")
    public String hello() {
        return "Hello World!";
    }
    
}
---------------------------------------------------------------------


== Build the _cloud-native-spring_ application

Return to the Terminal session you opened previously and make sure your working directory is set to be _devops-workshop-boeing/labs/my_work/cloud-native-spring_

. Find out what tasks are available to you with
+
  gradle tasks
  
. First we'll run tests
+
  gradle test

. Next we'll package the application as a libary artifact (it cannot be run on its own)
+
  gradle jar
  
. Next we'll package the application as an executable artifact (that can be run on its own because it will include all transitive dependencies along with embedding a servlet container)
+
  gradle bootRepackage


== Run the _cloud-native-spring_ application

Now we're ready to run the application

. Run the application with
+
  gradle bootRun

. You should see the application start up an embedded Apache Tomcat server on port 8080 (review terminal output):
+
[source,bash]
---------------------------------------------------------------------
2015-10-02 13:26:59.264  INFO 44749 --- [lication.main()] s.b.c.e.t.TomcatEmbeddedServletContainer: Tomcat started on port(s): 8080 (http)
2015-10-02 13:26:59.267  INFO 44749 --- [lication.main()] io.pivotal.CloudNativeSpringApplication: Started CloudNativeSpringApplication in 2.541 seconds (JVM running for 9.141)
---------------------------------------------------------------------

. Browse to http://localhost:8080/hello

. Stop the _cloud-native-spring_ application. In the terminal window type *Ctrl + C*

== Deploy _cloud-native-spring_ to Pivotal Cloud Foundry

We've built and run the application locally.  Now we'll deploy it to Cloud Foundry.

. Create an application manifest in the root folder _devops-workshop-boeing/labs/my_work/cloud-native-spring_
+
  touch manifest.yml

. Add application metadata, using a text editor (of choice)
+
[source, bash]
---------------------------------------------------------------------
---
applications:
- name: cloud-native-spring
  random-route: true
  instances: 1
  path: ./build/libs/cloud-native-spring-1.0-SNAPSHOT-exec.jar
  buildpack: java_buildpack
  env:
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
---------------------------------------------------------------------

. Push application into Cloud Foundry
+
  cf push
+
-> To specify an alternate buildpack, you could update the above to be e.g.,
+
  cf push -f manifest.yml -b java_buildpack_offline
+ 
Assuming the offline buildpack was installed and available for use with your targeted foundation.  You can check for which buildpacks are available by executing
+
  cf buildpacks

. Find the URL created for your app in the health status report. Browse to your app's /hello endpoint.

. Check the log output
+
  cf logs cloud-native-spring --recent

*Congratulations!* You’ve just completed your first Spring Boot application.
