= Labs

Welcome to the lab! Here you will find a collection of exercises and accompanying source-code.

== Overview

This workshop contains a number of lab folders meant to be worked through in numerical order - as each exercise builds upon the last. The only exception to this sequence is the *00* folder. This folder references sample applications in *samples*.  These applications can be pushed to Cloud Foundry at any time.

Your workspace is the *my_work* folder. If you get stuck implementing any of the labs, *solutions* are available for your perusal.


== PCF Environment Access

=== Account set up

. If you do not have an account yet, please see the instructor

=== Target the Environment

. If you haven't already, download the latest release of the Cloud Foundry CLI from https://github.com/cloudfoundry/cli/releases for your operating system and install it.

. Set the API target for the CLI (set appropriate end point for your environment):
+
*PWS*
+
----
$ cf api https://api.run.pivotal.io --skip-ssl-validation
----
+
or
+
*Boeing Pre-production*
+
----
$ cf login -a https://api.system.pcfpre-phx.cloud.boeing.com --sso
----

. Login to Pivotal Cloud Foundry:
+
----
$ cf login
----
+
Follow the prompts

== Apps Manager UI

. An alternative to installing the CF CLI is via your PCF Apps Manager interface.

. Navigate in a web browser to (depending on environment):
+
*PWS*
+
----
https://console.run.pivotal.io
----
+
or
+
*Boeing Pre-production*
+
----
https://login.system.pcfpre-phx.cloud.boeing.com/login
----

. Login to the interface with your email and password
+
-> Depending on how the workshop is conducted the password will be supplied to you by the instructor or you will use your own (from a pre-assigned Boeing account with WSSO access)

. Click the 'Tools' link, and download the CLI matching your operating system
